- name: Install and configure PostgreSQL
  hosts: databases
  remote_user: dbuser
  become: true
  become_user: yes
  roles:
    - role: './roles/postgresql'

- name: Configure nginx server
  hosts: webservers
  remote_user: servuser
  become: true
  become_user: yes
  roles:
    - role: './roles/nginx-webserver'