- name: Install and configure PostgreSQL
  hosts: databases
  #remote_user: 
  become_user: true
  roles:
    - role: './roles/postgresql'

- name: Configure nginx server
  hosts: webservers
  #remote_user: servuser
  become_user: true
  roles:
    - role: './roles/nginx-webserver'